# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    # Run tests using testng.xml
    mvn test -DsuiteXmlFile=testng.xml
    
    # Assuming the Extent Report is generated in a specific directory
    # Remove the old report before moving the new one
    rm -f $(Build.ArtifactStagingDirectory)/TestReport/Test-Automaton-Report.html
    
    # Move the updated report to the TestReport folder
    mv TestReport/Test-Automaton-Report.html $(Build.ArtifactStagingDirectory)/TestReport/
  displayName: 'Update and Move Extent Report in TestReport Folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ExtentReport'
    publishLocation: 'Container'