# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    rm -f TestReport/Test-Automaton-Report.html
    mvn test -DsuiteXmlFile=testng.xml
    
    mkdir -p $(Build.ArtifactStagingDirectory)/TestReport
    
    # Assuming the Extent Report is generated in a specific directory, move or copy it to TestReport folder
    # Make sure the path and filename are correct
    mv TestReport/Test-Automaton-Report.html $(Build.ArtifactStagingDirectory)/TestReport/
  displayName: 'Move Extent Report to TestReport Folder'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Test Run Title'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ExtentReport'
    publishLocation: 'Container'